# Test description:
#   Check that tracks get rebuilt when a publisher disconnects and reconnects.
#
# Test architecture:
#
# 1. Check that the subscriber receives the data sent by the publisher.
#
# ┌───────────────────┐             ┌────────────────────┐
# │  Domain 80        │             │         Domain 81  │
# │ ┌──────────────┐ ┌┼─────────────┼┐ ┌───────────────┐ │
# │ │publisher_t0_0│ ││  ddsrouter  ││ │subscriber_1_t0│ │
# │ │            ──┼─┼┤►           ─┼┼─┤►              │ │
# │ │(local)       │ ││  (local)    ││ │(local)        │ │
# │ └──────────────┘ └┼─────────────┼┘ └───────────────┘ │
# │                   │             │                    │
# └───────────────────┘             └────────────────────┘
#
# 2. Disconnect the publisher.
#
# ┌───────────────────┐             ┌────────────────────┐
# │  Domain 80        │             │         Domain 81  │
# │                  ┌┼─────────────┼┐ ┌───────────────┐ │
# │                  ││  ddsrouter  ││ │subscriber_1_t0│ │
# │                  ││             ││ │               │ │
# │                  ││  (local)    ││ │(local)        │ │
# │                  └┼─────────────┼┘ └───────────────┘ │
# │                   │             │                    │
# └───────────────────┘             └────────────────────┘
#
# 3. Check that when the publisher is reactivated, it receives the data sent by the publisher.
#
# ┌───────────────────┐             ┌────────────────────┐
# │  Domain 80        │             │         Domain 81  │
# │ ┌──────────────┐ ┌┼─────────────┼┐ ┌───────────────┐ │
# │ │publisher_t0_1│ ││  ddsrouter  ││ │subscriber_1_t0│ │
# │ │            ──┼─┼┤►           ─┼┼─┤►              │ │
# │ │(local)       │ ││  (local)    ││ │(local)        │ │
# │ └──────────────┘ └┼─────────────┼┘ └───────────────┘ │
# │                   │             │                    │
# └───────────────────┘             └────────────────────┘

services:

  # ROUTER
  ddsrouter:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: ddsrouter
    networks:
      - std_net
    volumes:
      - ./ddsrouter.yaml:/config.yaml
    command: ddsrouter -c /config.yaml --timeout 14


  # DOMAIN 80
  publisher_t0_0:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: publisher_t0_0
    depends_on:
      - ddsrouter
    networks:
      - std_net
    volumes:
      - ../../../../scripts:/scripts
    command: python3 /scripts/execute_and_validate_publisher.py --exe build/fastdds_configuration_example/configuration --timeout 5 --args "--samples 50 --domain 80 --name topic0 --interval 100"

  publisher_t0_1:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: publisher_t0_1
    depends_on:
      - ddsrouter
    networks:
      - std_net
    volumes:
      - ../../../../scripts:/scripts
    command: python3 /scripts/execute_and_validate_publisher.py --exe build/fastdds_configuration_example/configuration --timeout 5 --delay 6 --args "--samples 50 --domain 80 --name topic0 --interval 100"

  # DOMAIN 81
  subscriber_1_t0:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: subscriber_1_t0
    depends_on:
      - ddsrouter
    networks:
      - std_net
    volumes:
      - ../../../../scripts:/scripts
    command: python3 /scripts/execute_and_validate_subscriber.py --exe build/fastdds_configuration_example/configuration --samples 60 --allow-duplicates -1 --timeout 12 --args "--samples 60 --domain 81 --name topic0"

networks:
  std_net:
  default:
    driver: none
