# Test description:
#   This test checks the UDP functionality by creating 4 routers, 2 edges and 2 cloud.
#   The cloud router will forward every message from 1 to 2 by two different participants connected by UDP.
#   It also probes the Initial Peers functionality, avoiding the discovery of edge routers with those routers that
#    that are not the one suppose to connect with.
#
# Test architecture:
#
#            Domain 1            Domain 2
#   Server  <-------->  Router  <-------->  Client
#

services:

  ddsrouter:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: ddsrouter
    networks:
      - net_1
    volumes:
      - ./ddsrouter.yaml:/config.yaml
    command: ddsrouter -c /config.yaml --timeout 10

  ser_edge_1:
    image: ${DDSROUTER_COMPOSE_TEST_ROS2_DOCKER_IMAGE}
    container_name: ser_edge_1
    depends_on:
      - ddsrouter
    networks:
      - net_1
    environment:
      - ROS_DOMAIN_ID=1
    volumes:
      - ../scripts:/scripts
    command: python3 /scripts/execute_and_validate_server.py --samples 10 --timeout 10

  cli_edge_2:
    image: ${DDSROUTER_COMPOSE_TEST_ROS2_DOCKER_IMAGE}
    container_name: cli_edge_2
    depends_on:
      - ddsrouter
    networks:
      - net_1
    environment:
      - ROS_DOMAIN_ID=2
    volumes:
      - ../scripts:/scripts
    command: python3 /scripts/execute_and_validate_client.py --samples 10 --timeout 10

networks:
  net_1:
  default:
    driver: none
