# Test description:
#   This test checks the TCP functionality by creating 3 routers, 2 edges and 1 cloud.
#   The cloud router will forward every message from 1 to 2 by two different participants connected by TCP.
#   It also probes the Initial Peers functionality, avoiding the discovery of edge router.
#
# Test architecture:
#
#          ┌────────────────────────────────────────────────────────────────┐
#          │ cloud_edge_net                                                 │
#          │                                                                │
#          │                        ┌──────────────────┐                    │
#          │                        │ ddsrouter_cloud  │                    │
#          │                        │ (wan + wan)      │                    │
#          │                        └─▲──────────────▲─┘                    │
#          │                          │              │                      │
#          │           ┌──────────────┘              └─────────┐            │
#   ┌──────┼───────────┼──────────────────┐        ┌───────────┼────────────┼──────┐
#   │      │           │                  │        │           │            │      │
#   │      │ ┌─────────▼────────┐         │        │   ┌───────▼──────────┐ │      │
#   │      │ │ ddsrouter_edge_1 │         │        │   │ ddsrouter_edge_2 │ │      │
#   │      │ │ (local + wan)    │         │        │   │ (local + wan)    │ │      │
#   │      │ └───────┬────▲─────┘         │        │   └───────┬──────────┘ │      │
#   │      │         │    │               │        │           │            │      │
#   │      └─────────┼────┼───────────────┼────────┼───────────┼────────────┘      │
#   │                │    │               │        │           │                   │
#   │  ┌─────────────▼┐  ┌┴───────────┐   │        │    ┌──────▼───────┐           │
#   │  │ sub_edge_1   │  │ pub_edge_1 │   │        │    │ sub_edge_2   │           │
#   │  │ (subscriber) │  │ (publisher)│   │        │    │ (subscriber) │           │
#   │  └──────────────┘  └────────────┘   │        │    └──────────────┘           │
#   │                                     │        │                               │
#   │ edge_1_net (domain 1)               │        │         edge_2_net (domain 2) │
#   └─────────────────────────────────────┘        └───────────────────────────────┘

services:

  ddsrouter_cloud:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: ddsrouter_cloud
    networks:
      - cloud_edge_net
    volumes:
      - ./ddsrouter_cloud.yaml:/config.yaml
    command: bash -c "source /root/DDS-Router/install/setup.bash && ddsrouter -c /config.yaml --timeout 10"

  ddsrouter_edge_1:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: ddsrouter_edge_1
    depends_on:
      - ddsrouter_cloud
    networks:
      - cloud_edge_net
      - edge_1_net
    volumes:
      - ./ddsrouter_edge_1.yaml:/config.yaml
    command: bash -c "source /root/DDS-Router/install/setup.bash && ddsrouter -c /config.yaml --timeout 10"

  pub_edge_1:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: pub_edge_1
    depends_on:
      - ddsrouter_edge_1
    networks:
      - edge_1_net
    command: install/BasicConfigurationExample/examples/cpp/dds/BasicConfigurationExample/BasicConfigurationExample publisher -i 200 -s 45 -d 1

  sub_edge_1:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: sub_edge_1
    depends_on:
      - ddsrouter_edge_1
    networks:
      - edge_1_net
    volumes:
      - ../scripts:/scripts
    command: python3 /scripts/execute_and_validate_subscriber.py --exe install/BasicConfigurationExample/examples/cpp/dds/BasicConfigurationExample/BasicConfigurationExample --samples 10 --timeout 10 --domain 1

  ddsrouter_edge_2:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: ddsrouter_edge_2
    depends_on:
      - ddsrouter_cloud
    networks:
      - cloud_edge_net
      - edge_2_net
    volumes:
      - ./ddsrouter_edge_2.yaml:/config.yaml
    command: bash -c "source /root/DDS-Router/install/setup.bash && ddsrouter -c /config.yaml --timeout 10"

  sub_edge_2:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: sub_edge_2
    depends_on:
      - ddsrouter_edge_2
    networks:
      - edge_2_net
    volumes:
      - ../scripts:/scripts
    command: python3 /scripts/execute_and_validate_subscriber.py --exe install/BasicConfigurationExample/examples/cpp/dds/BasicConfigurationExample/BasicConfigurationExample --samples 10 --timeout 10 --domain 2

networks:
  edge_1_net:
  edge_2_net:
  cloud_edge_net:
  default:
    driver: none
