# Test description:
#   This test checks the Discovery Server functionality, by creating a Router Discovery Server blocking every topic.
#   The edge routers must discover each other via Discovery Server and transmit data from one another.
#
# Test architecture:
#
#          ┌────────────────────────────────────────────────────────────────┐
#          │ cloud_edge_net                                                 │
#          │                                                                │
#          │                        ┌──────────────────┐                    │
#          │                        │ ddsrouter_cloud  │                    │
#          │                        │ (ds_wan | block) │                    │
#          │                        └─▲──────────────▲─┘                    │
#          │                          │              │                      │
#          │           ┌--------------┘              └---------┐            │
#   ┌──────┼───────────┼──────────────────┐        ┌───────────┼────────────┼──────┐
#   │      │           │                  │        │           │            │      │
#   │      │ ┌─────────▼────────┐         │        │   ┌───────▼──────────┐ │      │
#   │      │ │ ddsrouter_edge_1 │──────────────────────│ ddsrouter_edge_2 │ │      │
#   │      │ │ (local + ds_wan) │         │        │   │ (local + ds_wan) │ │      │
#   │      │ └───────┬────▲─────┘         │        │   └───────┬──────────┘ │      │
#   │      │         │    │               │        │           │            │      │
#   │      └─────────┼────┼───────────────┼────────┼───────────┼────────────┘      │
#   │                │    │               │        │           │                   │
#   │  ┌─────────────▼┐  ┌┴───────────┐   │        │    ┌──────▼───────┐           │
#   │  │ sub_edge_1   │  │ pub_edge_1 │   │        │    │ sub_edge_2   │           │
#   │  │ (subscriber) │  │ (publisher)│   │        │    │ (subscriber) │           │
#   │  └──────────────┘  └────────────┘   │        │    └──────────────┘           │
#   │                                     │        │                               │
#   │ edge_1_net (domain 1)               │        │         edge_2_net (domain 2) │
#   └─────────────────────────────────────┘        └───────────────────────────────┘

services:

  ddsrouter_cloud:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: ddsrouter_cloud
    networks:
      - cloud_edge_net
    volumes:
      - ./ddsrouter_cloud_discovery.yaml:/config.yaml
    command: ddsrouter -c /config.yaml --timeout 10

  ddsrouter_edge_1:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: ddsrouter_edge_1
    depends_on:
      - ddsrouter_cloud
    networks:
      - cloud_edge_net
      - edge_1_net
    volumes:
      - ./ddsrouter_edge_1.yaml:/config.yaml
    command: ddsrouter -c /config.yaml --timeout 10

  pub_edge_1:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: pub_edge_1
    depends_on:
      - ddsrouter_edge_1
    networks:
      - edge_1_net
    command: install/BasicConfigurationExample/examples/cpp/dds/BasicConfigurationExample/BasicConfigurationExample publisher -i 250 -s 30 -d 1

  sub_edge_1:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: sub_edge_1
    depends_on:
      - ddsrouter_edge_1
    networks:
      - edge_1_net
    volumes:
      - ../execute_and_validate_subscriber.py:/execute_and_validate_subscriber.py
    command: python3 /execute_and_validate_subscriber.py --exe install/BasicConfigurationExample/examples/cpp/dds/BasicConfigurationExample/BasicConfigurationExample --samples 10 --timeout 10 --domain 1

  ddsrouter_edge_2:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: ddsrouter_edge_2
    depends_on:
      - ddsrouter_cloud
    networks:
      - cloud_edge_net
      - edge_2_net
    volumes:
      - ./ddsrouter_edge_2.yaml:/config.yaml
    command: ddsrouter -c /config.yaml --timeout 10

  sub_edge_2:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: sub_edge_2
    depends_on:
      - ddsrouter_edge_2
    networks:
      - edge_2_net
    volumes:
      - ../execute_and_validate_subscriber.py:/execute_and_validate_subscriber.py
    command: python3 /execute_and_validate_subscriber.py --exe install/BasicConfigurationExample/examples/cpp/dds/BasicConfigurationExample/BasicConfigurationExample --samples 10 --timeout 10 --domain 2

networks:
  edge_1_net:
  edge_2_net:
  cloud_edge_net:
  default:
    driver: none
