name: mirror-branch

on:
  push:
    branches:
      - 'main'

jobs:
  mirror_job_main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Mirror main branch to API & ABI compatible minor version branches
    strategy:
      fail-fast: false
      matrix:
          dest_branch:
          - '3.x'
    steps:
      - name: Mirror action step
        id: mirror
        uses: eProsima/eProsima-CI/external/mirror-branch-action@feature/test-reporting
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            source: 'main'
            dest: ${{ matrix.dest_branch }}
